# Generated by Django 4.2.6 on 2023-10-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_github_link_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration_unit',
            field=models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('days', 'Days')], default='years', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
