# Generated by Django 4.2.6 on 2023-10-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_duration_unit_alter_project_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='google_drive_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
