# Generated by Django 4.2.6 on 2023-10-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_google_drive_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='google_drive_link',
        ),
    ]
